# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b31oBfrTSXn6kcn83KcmKvoSUh7g3nme
"""

#Task1 Assignment no 2

for i in range(2000,3000,1):
  if(i%7==0):
    print(i, end=",")

# Task 1:-Assignment No:-3

fname = input("Input your First Name : ")
lname = input("Input your Last Name : ")
print ("Hello  " + lname[: : -1] + " " + fname[::-1])

##Task1 Assignment no 4

pi=3.14
r=12
V=4/3*pi*r**3

print ("Value of P is:-", V)

"""Task2:-Assignment no:**1**"""

Number=input("enter value:-")
list1=Number.split(",")
print("list:",list1)

# Task2:- Assignment No2
n=5

for i in range(n):
  for j in range(i):
     print ('*', end="")
  print("")

for t in range(n,0,-1):
  for k in range (t):
    print('*',end="")
  print("")

# Task2:- Assignment No3

Name=input("Enter your Name:-")
print(Name[::-1])

# Task2:- Assignment No4

print("""WE, THE PEOPLE OF INDIA,\n having solemnly resolved to constitute India into a
SOVEREIGN,! \n SOCIALIST, SECULAR, DEMOCRATIC REPUBLIC \nand to secure to all
its citizens""")

